name: deploy

on:
    push:
        branches: [ master, develop ]

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2.3.1
                with:
                    ref: master

            -   name: Set up JDK 17
                uses: actions/setup-java@v1
                with:
                    java-version: 17

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Build master branch
                run: ./gradlew build

            -   name: Check out develop branch
                uses: actions/checkout@v2.3.1
                with:
                    ref: develop
                    path: beta
                    clean: false

            -   name: Build develop branch
                run: |
                    cd beta
                    ./gradlew build
                    mkdir ../build/distributions/beta
                    cp -r build/distributions/* ../build/distributions/beta

            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v1
                with:
                    path: './build/distributions'
